# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  #orderer0.example.com:
  #orderer1.example.com:
  #orderer2.example.com:
  peer0.org1.example.com:

networks:
  test:

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - GODEBUG=netdns=go
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
     # - ORDERER_HOST=orderer.example.com #ws add
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    extra_hosts:
      # org1: UML; org2: UW
      # - "orderer.example.com:54.210.204.251"
      # - "peer0.org1.example.com:54.210.204.251"
      # - "peer1.org1.example.com:107.22.48.133"
      # - "peer2.org1.example.com:54.175.11.179"
      # - "peer0.org2.example.com:54.85.126.114"
      # - "peer1.org2.example.com:54.197.127.36"
      # - "peer2.org2.example.com:3.92.185.56"
      - "orderer.example.com:${HOST1_PUB_IP}"
      - "peer0.org1.example.com:${HOST1_PUB_IP}"
      - "peer1.org1.example.com:${HOST2_PUB_IP}"
      - "peer2.org1.example.com:${HOST3_PUB_IP}"
      - "peer0.org2.example.com:${HOST4_PUB_IP}"
      - "peer1.org2.example.com:${HOST5_PUB_IP}"
      - "peer2.org2.example.com:${HOST6_PUB_IP}"
    ports:
      - 7050:7050
    networks:
      - test

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      #Generic peer variables
      - GODEBUG=netdns=go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      # following two entries removed by Fabric 2.2, check https://hyperledger-fabric.readthedocs.io/en/release-2.2/gossip.html
      # that means, in default setting, we use static leader mechanism, namely, org admin
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # CORE_PEER_GOSSIP_BOOTSTRAP should be set with the anchor peer, which is the startup peer
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.example.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    extra_hosts:
      # org1: UML; org2: UW
      # - "orderer.example.com:54.210.204.251"
      # - "peer0.org1.example.com:54.210.204.251"
      # - "peer1.org1.example.com:107.22.48.133"
      # - "peer2.org1.example.com:54.175.11.179"
      # - "peer0.org2.example.com:54.85.126.114"
      # - "peer1.org2.example.com:54.197.127.36"
      # - "peer2.org2.example.com:3.92.185.56"
      - "orderer.example.com:${HOST1_PUB_IP}"
      - "peer0.org1.example.com:${HOST1_PUB_IP}"
      - "peer1.org1.example.com:${HOST2_PUB_IP}"
      - "peer2.org1.example.com:${HOST3_PUB_IP}"
      - "peer0.org2.example.com:${HOST4_PUB_IP}"
      - "peer1.org2.example.com:${HOST5_PUB_IP}"
      - "peer2.org2.example.com:${HOST6_PUB_IP}"
    ports:
      - 7051:7051
    networks:
      - test
